version: '1'

networks:
  prodnetwork:
    driver: bridge

services:
 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
  depends_on:
    - gitlab
    - sonar
  environment:
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

 sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   - "5432:5432"
  networks:
    - prodnetwork
  depends_on:
    - sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
 sonardb:
  networks:
    - prodnetwork
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

 db2:
  image: postgres
  environment:
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=gitlab
    - POSTGRES_DB=gitlab
  networks:
    - prodnetwork
 gitlab:
  image: sameersbn/gitlab:8.3.2
  ports:
    - "10080:80"
    - "10022:22"
  networks:
    - prodnetwork
  depends_on:
    - db2
    - redis
  environment:
    - DB_HOST=db2
    - DB_NAME=gitlab
    - DB_USER=gitlab
    - DB_PASS=gitlab
    - REDIS_HOST=redisio

    - TZ=Europe/Paris
    - GITLAB_TIMEZONE=Paris

    - GITLAB_SECRETS_DB_KEY_BASE=Ln7grYIP2ZN1Rh5VFmBydaSNHAMGi1ql

    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=253c228099-36615c@inbox.mailtrap.io
    - GITLAB_EMAIL_REPLY_TO=253c228099-36615c@inbox.mailtrap.io
    - GITLAB_INCOMING_EMAIL_ADDRESS=253c228099-36615c@inbox.mailtrap.io

    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=true
    - SMTP_DOMAIN=mailtrap.io
    - SMTP_HOST=mailtrap.io
    - SMTP_PORT=2525
    - SMTP_USER=25766163a20e5f7b1
    - SMTP_PASS=1966928ed776a5
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
 redis:
  image: sameersbn/redis:latest
  networks:
    - prodnetwork
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
