version: '2'

services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.4-21
    env_file: config
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql

  gitlab:
    restart: always
    image: sameersbn/gitlab:8.7.5
    env_file: config
    links:
      - redis:redis
      - postgresql:postgresql
    ports:
      - "10080:80"
      - "10022:22"
    depends_on:
      - postgresql
      - redis
    volumes:
      - /srv/docker/gitlab:/home/git/data

  redis:
    restart: always
    image: sameersbn/redis:latest
    env_file: config
    volumes:
      - /srv/docker/redis:/var/lib/redis

  jenkins:
    restart: always
    build: ./jenkins
    env_file: config
    ports:
      - "18080:8080"
    volumes:
      - /srv/docker/jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
      - "5432:5432"
    links:
      - sonardb:postgresql
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar

  sonardb:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /srv/docker/sonardb:/var/lib/postgresql





